version: '3.7'

services:
    nginx:
        image: nginx:latest
        container_name: "${PROJECT_NAME}_nginx"
        volumes:
            - ./.docker/nginx/conf.d/:/etc/nginx/conf.d
            - ./:/var/www/
        ports:
            - "80:80"
        depends_on:
            - app

    app:
        build:
            context: .
            dockerfile: .docker/app/Dockerfile
        container_name: "${PROJECT_NAME}_app"
        volumes:
            - ./:/var/www
        depends_on:
            - db

    db:
        image: postgres:15
        container_name: "${PROJECT_NAME}_db"
        restart: always
        volumes:
            - db:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
             POSTGRES_PASSWORD: ${DB_PASSWORD}
             POSTGRES_USER: ${DB_USERNAME}
             POSTGRES_DB: ${DB_DATABASE}

    pgadmin:
        image: dpage/pgadmin4:latest
        container_name: "${PROJECT_NAME}_pgadmin"
        ports:
            - "${PGADMIN_PORT}:80"
        depends_on:
            - db
        environment:
              PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
              PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}

    redis:
        image: redis:latest
        container_name: "${PROJECT_NAME}_redis"
        restart: always
        ports:
            - "6379:6379"
        volumes:
            - redis:/data
        depends_on:
            - app

volumes:
  db:
    name: ${PROJECT_NAME}_pgsql
  redis:
    name: ${PROJECT_NAME}_redis

#Docker Networks
networks:
    app-network:
        driver: bridge
